
version: '3.7'
services:
  app:
    container_name: student_grouper
    build: .
    stdin_open: true
    tty: true
    ports:
      - '5050:5050'
    hostname: 0.0.0.0
    volumes:
      - ./app:/app

  redis:
      image: 'redis:3.2.10'
      container_name: redis
      command: redis-server
      ports:
        - '6379:6379'
